name: CI

on: [push]

jobs:
  build-event-handler:
    name: Build the Event Handler
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: event-handler
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Install Dependencies
        run: yarn

      - name: Lint
        run: yarn lint

  tag:
    name: Tag the release
    runs-on: ubuntu-latest
    needs: [build-event-handler]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: tag
        id: tag
        uses: tcpl/semver-tag-creator-action@1.3.3
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        with:
          major-version: 1
